package ec.edu.ups.pwp.EVABoniJuanCLI;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T12:02:10.477-05:00
 * Generated source version: 3.5.0
 *
 */
@WebServiceClient(name = "AutomovilesServiceSOAPService",
                  wsdlLocation = "http://localhost:8080/EVABoniJuanSRV/AutomovilesServiceSOAP?wsdl",
                  targetNamespace = "http://bean.EVABoniJuanSRV.pwp.ups.edu.ec/")
public class AutomovilesServiceSOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://bean.EVABoniJuanSRV.pwp.ups.edu.ec/", "AutomovilesServiceSOAPService");
    public final static QName AutomovilesServiceSOAPPort = new QName("http://bean.EVABoniJuanSRV.pwp.ups.edu.ec/", "AutomovilesServiceSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/EVABoniJuanSRV/AutomovilesServiceSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AutomovilesServiceSOAPService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/EVABoniJuanSRV/AutomovilesServiceSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AutomovilesServiceSOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AutomovilesServiceSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutomovilesServiceSOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AutomovilesServiceSOAPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AutomovilesServiceSOAPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AutomovilesServiceSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AutomovilesServiceSOAP
     */
    @WebEndpoint(name = "AutomovilesServiceSOAPPort")
    public AutomovilesServiceSOAP getAutomovilesServiceSOAPPort() {
        return super.getPort(AutomovilesServiceSOAPPort, AutomovilesServiceSOAP.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutomovilesServiceSOAP
     */
    @WebEndpoint(name = "AutomovilesServiceSOAPPort")
    public AutomovilesServiceSOAP getAutomovilesServiceSOAPPort(WebServiceFeature... features) {
        return super.getPort(AutomovilesServiceSOAPPort, AutomovilesServiceSOAP.class, features);
    }

}
