package ec.edu.ups.pwp.EVABoniJuanCLI;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T12:02:10.472-05:00
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://bean.EVABoniJuanSRV.pwp.ups.edu.ec/", name = "AutomovilesServiceSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface AutomovilesServiceSOAP {

    @WebMethod
    @RequestWrapper(localName = "getAutomoviles", targetNamespace = "http://bean.EVABoniJuanSRV.pwp.ups.edu.ec/", className = "ec.edu.ups.pwp.EVABoniJuanCLI.GetAutomoviles")
    @ResponseWrapper(localName = "getAutomovilesResponse", targetNamespace = "http://bean.EVABoniJuanSRV.pwp.ups.edu.ec/", className = "ec.edu.ups.pwp.EVABoniJuanCLI.GetAutomovilesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ec.edu.ups.pwp.EVABoniJuanCLI.Automovil> getAutomoviles()
;

    @WebMethod
    @RequestWrapper(localName = "crearAutomovil", targetNamespace = "http://bean.EVABoniJuanSRV.pwp.ups.edu.ec/", className = "ec.edu.ups.pwp.EVABoniJuanCLI.CrearAutomovil")
    @ResponseWrapper(localName = "crearAutomovilResponse", targetNamespace = "http://bean.EVABoniJuanSRV.pwp.ups.edu.ec/", className = "ec.edu.ups.pwp.EVABoniJuanCLI.CrearAutomovilResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String crearAutomovil(

        @WebParam(name = "arg0", targetNamespace = "")
        ec.edu.ups.pwp.EVABoniJuanCLI.Automovil arg0
    );
}
